# Generated by Django 4.2.29 on 2026-05-31 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesession',
            name='join_code',
        ),
        migrations.AddField(
            model_name='table',
            name='code_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='daily_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
