# Generated by Django 4.2.29 on 2026-05-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('menu', '0002_menuitemvariant'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitemvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('session', 'menu_item', 'variant')},
        ),
    ]
