# Generated by Django 4.2.29 on 2026-05-31 23:15

from django.db import migrations


VARIANT_DATA = {
    # Soups
    'Pho': [
        ('Rare Beef', 18),
        ('Rare Beef and Beef Balls', 19),
    ],
    'Udon': [
        ('Vegetable', 17),
        ('Chicken', 18),
        ('Beef', 18),
        ('Tempura', 19),
    ],
    'Sate Pho': [
        ('Rare Beef', 19),
        ('Rare Beef and Beef Balls', 20),
    ],
    # Entrees
    'Teppanyaki Hot Plate': [
        ('Tofu', 19),
        ('Katsu', 19),
        ('Chicken', 19),
        ('Chicken - White Meat', 20),
        ('Beef', 20),
        ('Salmon', 23),
        ('Mixed Seafood', 23),
    ],
    'Red Curry': [
        ('Vegetable', 17),
        ('Tofu', 17),
        ('Chicken', 18),
        ('Prawn', 19),
        ('Seafood', 22),
    ],
    'Vietnamese Rice Plate': [
        ('Pork Chop', 18),
        ('Lemongrass Chicken', 19),
    ],
    # From the Wok
    'Yang Chow Fried Rice': [
        ('Vegetable', 16),
        ('Chicken', 17),
        ('BBQ Pork', 17),
    ],
    'Yaki Soba': [
        ('Vegetable', 18),
        ('Chicken', 19),
        ('Beef', 20),
    ],
    # Salad
    'Sunomono': [
        ('Plain', 5),
        ('Shrimp', 6),
        ('Octopus', 7),
    ],
}


def seed_variants(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    MenuItemVariant = apps.get_model('menu', 'MenuItemVariant')

    for item_name, variants in VARIANT_DATA.items():
        try:
            item = MenuItem.objects.get(name=item_name)
        except MenuItem.DoesNotExist:
            # Item doesn't exist yet, skip
            continue

        # Set the parent item price to the lowest variant price
        lowest_price = min(v[1] for v in variants)
        item.price = lowest_price
        item.save()

        for variant_name, price in variants:
            MenuItemVariant.objects.get_or_create(
                menu_item=item,
                name=variant_name,
                defaults={'price': price},
            )


def reverse_seed(apps, schema_editor):
    MenuItemVariant = apps.get_model('menu', 'MenuItemVariant')
    MenuItemVariant.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitemvariant'),
    ]

    operations = [
        migrations.RunPython(seed_variants, reverse_seed),
    ]
